/**
 * Central registry of user-visible Russian strings.
 * The Playwright assertNoEnglish helper verifies that no English leaks into the DOM.
 * Keep groups per feature; add new keys here before referencing them in components.
 */

export const strings = {
  app: {
    title: 'Strateva',
    subtitle: 'Инструмент стратегического ИТ- и бизнес-планирования',
    loading: 'Загрузка…',
    error: 'Произошла ошибка',
    retry: 'Повторить',
    cancel: 'Отмена',
    confirm: 'Подтвердить',
    save: 'Сохранить',
    delete: 'Удалить',
    back: 'Назад',
  },
  nav: {
    dashboard: 'Главная',
    goals: 'Стратегические цели',
    backlogs: 'Бэклоги',
    tasks: 'Задачи',
    analytics: 'Панель аналитики',
    reports: 'Отчёты',
    audit: 'Журнал аудита',
    users: 'Пользователи',
    logout: 'Выйти',
  },
  auth: {
    loginTitle: 'Вход в систему',
    loginSubtitle: 'Введите учётные данные, чтобы продолжить',
    usernameLabel: 'Логин',
    usernamePlaceholder: 'Например, pm',
    passwordLabel: 'Пароль',
    passwordPlaceholder: 'Ваш пароль',
    submit: 'Войти',
    submitting: 'Выполняется вход…',
    requiredUsername: 'Введите логин',
    requiredPassword: 'Введите пароль',
    invalidCredentials: 'Неверный логин или пароль',
    sessionExpired: 'Сеанс истёк, войдите повторно',
    loggedInAs: 'Вы вошли как',
    demoHint: 'Демонстрационная среда',
    role: {
      PROJECT_MANAGER: 'Менеджер проектов',
      BUSINESS_ANALYST: 'Бизнес-аналитик',
      EMPLOYEE: 'Сотрудник',
    },
  },
  marketing: {
    tagline: 'Стратегическое планирование для вашего бизнеса',
    description:
      'Единое пространство для постановки целей, управления бэклогом и анализа результатов.',
    bullets: [
      'Единая карта стратегических целей',
      'Управление бэклогом и задачами',
      'Отчёты и журнал аудита действий',
    ],
  },
  dashboard: {
    welcome: 'Добро пожаловать',
    overview: 'Краткий обзор рабочего пространства',
    roleLabel: 'Роль',
    statsTotal: 'Всего',
    openList: 'Перейти к списку',
    loadingStats: '—',
    cards: {
      goals: {
        title: 'Стратегические цели',
        description: 'Формулируйте и отслеживайте ключевые цели компании',
        statsActive: 'Активные',
      },
      backlogs: {
        title: 'Бэклоги',
        description: 'Ведите бэклог инициатив и задач',
        statsPending: 'На согласовании',
      },
      tasks: {
        title: 'Задачи',
        description: 'Отслеживайте операционные задачи команды',
        statsInProgress: 'В работе',
        statsMine: 'Мои в работе',
      },
      reports: {
        title: 'Отчёты и аналитика',
        description: 'Аналитические сводки по целям, KPI и задачам',
        statsOverdue: 'Просрочено задач',
        openAnalytics: 'Открыть аналитику',
      },
      audit: {
        title: 'Журнал аудита',
        description: 'История изменений и действий пользователей',
        statsToday: 'За последние 24 ч.',
        openAudit: 'Открыть журнал',
      },
    },
  },
  errors: {
    network: 'Сеть недоступна. Проверьте соединение.',
    forbidden: 'Недостаточно прав для выполнения операции',
    notFound: 'Запрашиваемый ресурс не найден',
    unknown: 'Непредвиденная ошибка. Повторите попытку позже.',
  },
  goals: {
    title: 'Стратегические цели',
    subtitle: 'Формулируйте цели и отслеживайте ключевые показатели эффективности',
    empty: 'Стратегические цели не найдены',
    emptyHint: 'Создайте первую цель, чтобы начать планирование',
    createButton: 'Создать цель',
    backToList: 'К списку целей',
    searchPlaceholder: 'Поиск по наименованию',
    statusFilterLabel: 'Статус',
    statusFilterAll: 'Все статусы',
    columns: {
      title: 'Наименование',
      period: 'Период',
      priority: 'Приоритет',
      status: 'Статус',
      kpis: 'KPI',
      createdAt: 'Дата создания',
    },
    form: {
      createTitle: 'Новая стратегическая цель',
      editTitle: 'Редактирование цели',
      titleLabel: 'Наименование цели',
      titlePlaceholder: 'Например, «Увеличить выручку на 25%»',
      descriptionLabel: 'Описание',
      descriptionPlaceholder: 'Краткое описание цели и контекста',
      periodStartLabel: 'Начало периода',
      periodEndLabel: 'Окончание периода',
      priorityLabel: 'Приоритет',
      kpisTitle: 'Ключевые показатели эффективности',
      kpisHint: 'Добавьте минимум один KPI для цели',
      addKpi: 'Добавить KPI',
      removeKpi: 'Удалить',
      kpiName: 'Наименование',
      kpiTarget: 'Целевое значение',
      kpiCurrent: 'Текущее значение',
      kpiUnit: 'Единица измерения',
      kpiUnitPlaceholder: 'шт., руб., %',
      submit: 'Сохранить цель',
      submitting: 'Сохранение…',
      validation: {
        titleRequired: 'Введите наименование цели',
        titleTooLong: 'Не более 200 символов',
        periodStartRequired: 'Укажите дату начала периода',
        periodEndRequired: 'Укажите дату окончания периода',
        periodOrder: 'Дата окончания должна быть позже даты начала',
        priorityRequired: 'Укажите приоритет',
        atLeastOneKpi: 'Добавьте хотя бы один ключевой показатель эффективности',
        kpiNameRequired: 'Введите наименование показателя',
        kpiTargetRequired: 'Укажите целевое значение',
        kpiTargetNonNegative: 'Значение не может быть отрицательным',
      },
    },
    detail: {
      periodLabel: 'Период',
      priorityLabel: 'Приоритет',
      statusLabel: 'Статус',
      createdAtLabel: 'Создана',
      createdByLabel: 'Автор',
      kpisTitle: 'Ключевые показатели эффективности',
      noKpis: 'KPI ещё не добавлены',
      targetLabel: 'Цель',
      currentLabel: 'Факт',
    },
    actions: {
      edit: 'Редактировать',
      submitForApproval: 'Отправить на согласование',
      activate: 'Активировать',
      complete: 'Завершить',
      archive: 'Перевести в архив',
      delete: 'Удалить',
      confirmDelete: 'Удалить цель без возможности восстановления?',
    },
    status: {
      DRAFT: 'Черновик',
      SUBMITTED: 'На согласовании',
      ACTIVE: 'Активна',
      COMPLETED: 'Завершена',
      ARCHIVED: 'В архиве',
    },
    priority: {
      LOW: 'Низкий',
      MEDIUM: 'Средний',
      HIGH: 'Высокий',
      CRITICAL: 'Критический',
    },
    toast: {
      created: 'Цель создана',
      updated: 'Цель обновлена',
      submitted: 'Цель отправлена на согласование',
      activated: 'Цель переведена в статус «Активна»',
      completed: 'Цель завершена',
      archived: 'Цель перенесена в архив',
      deleted: 'Цель удалена',
    },
  },
  backlog: {
    title: 'Бэклоги',
    subtitle: 'Формируйте бэклоги инициатив по стратегическим целям',
    empty: 'Бэклоги не найдены',
    emptyHint: 'Создайте первый бэклог, чтобы начать планирование',
    createButton: 'Создать бэклог',
    backToList: 'К списку бэклогов',
    searchPlaceholder: 'Поиск по наименованию',
    statusFilterLabel: 'Статус',
    statusFilterAll: 'Все статусы',
    columns: {
      title: 'Наименование',
      goal: 'Стратегическая цель',
      status: 'Статус',
      items: 'Элементов',
      createdBy: 'Автор',
      createdAt: 'Дата создания',
    },
    form: {
      createTitle: 'Новый бэклог',
      titleLabel: 'Наименование бэклога',
      titlePlaceholder: 'Например, «Запуск новой платформы»',
      goalLabel: 'Стратегическая цель',
      goalPlaceholder: 'Выберите цель',
      submit: 'Создать бэклог',
      submitting: 'Сохранение…',
      noGoals: 'Нет доступных стратегических целей',
      validation: {
        titleRequired: 'Введите наименование бэклога',
        titleTooLong: 'Не более 200 символов',
        goalRequired: 'Выберите стратегическую цель',
      },
    },
    detail: {
      goalLabel: 'Стратегическая цель',
      statusLabel: 'Статус',
      createdAtLabel: 'Создан',
      createdByLabel: 'Автор',
      submittedAtLabel: 'Отправлен',
      signedAtLabel: 'Подписан',
      signedByLabel: 'Подписал',
      cancelledAtLabel: 'Сторнирован',
      cancelledByLabel: 'Сторнировал',
      itemsTitle: 'Элементы бэклога',
      noItems: 'Элементы ещё не добавлены',
      addItem: 'Добавить элемент',
      itemsHint: 'Добавьте элементы бэклога, прежде чем отправлять его на согласование',
    },
    itemForm: {
      titleLabel: 'Наименование элемента',
      titlePlaceholder: 'Например, «Подготовить техническое задание»',
      descriptionLabel: 'Описание',
      descriptionPlaceholder: 'Дополнительный контекст по элементу',
      priorityLabel: 'Приоритет',
      submitCreate: 'Добавить',
      submitUpdate: 'Сохранить',
      validation: {
        titleRequired: 'Введите наименование элемента',
        titleTooLong: 'Не более 200 символов',
        descriptionTooLong: 'Не более 2000 символов',
        priorityRequired: 'Укажите приоритет',
      },
    },
    actions: {
      edit: 'Редактировать',
      remove: 'Удалить',
      submitForApproval: 'Отправить на согласование',
      sign: 'Подписать',
      cancel: 'Сторнировать',
      confirmRemoveItem: 'Удалить элемент бэклога?',
      confirmSubmit: 'Отправить бэклог на согласование?',
      confirmSign: 'Подписать бэклог?',
      confirmCancel: 'Сторнировать бэклог без возможности восстановления?',
    },
    status: {
      DRAFT: 'Черновик',
      SUBMITTED: 'На согласовании',
      SIGNED: 'Подписан',
      CANCELLED: 'Сторнирован',
    },
    toast: {
      created: 'Бэклог создан',
      itemAdded: 'Элемент добавлен',
      itemUpdated: 'Элемент обновлён',
      itemRemoved: 'Элемент удалён',
      submitted: 'Бэклог отправлен на согласование',
      signed: 'Бэклог подписан',
      cancelled: 'Бэклог сторнирован',
    },
  },
  tasks: {
    title: 'Задачи',
    subtitle: 'Планируйте и выполняйте операционные задачи',
    empty: 'Задачи не найдены',
    emptyHint: 'Создайте первую задачу, чтобы начать работу',
    emptyEmployeeHint: 'Пока нет задач, назначенных на вас',
    createButton: 'Создать задачу',
    backToList: 'К списку задач',
    searchPlaceholder: 'Поиск по наименованию',
    statusFilterLabel: 'Статус',
    statusFilterAll: 'Все статусы',
    priorityFilterLabel: 'Приоритет',
    priorityFilterAll: 'Любой приоритет',
    viewTable: 'Таблица',
    viewBoard: 'Доска',
    unassigned: 'Не назначен',
    columns: {
      title: 'Наименование',
      goal: 'Стратегическая цель',
      priority: 'Приоритет',
      status: 'Статус',
      assignee: 'Исполнитель',
      deadline: 'Срок',
      createdAt: 'Создана',
    },
    form: {
      createTitle: 'Новая задача',
      editTitle: 'Редактирование задачи',
      titleLabel: 'Наименование задачи',
      titlePlaceholder: 'Например, «Подготовить архитектурную схему»',
      descriptionLabel: 'Описание',
      descriptionPlaceholder: 'Дополнительный контекст по задаче',
      goalLabel: 'Стратегическая цель',
      goalPlaceholder: 'Выберите цель',
      priorityLabel: 'Приоритет',
      deadlineLabel: 'Срок выполнения',
      submitCreate: 'Создать задачу',
      submitUpdate: 'Сохранить изменения',
      submitting: 'Сохранение…',
      noGoals: 'Нет доступных стратегических целей',
      validation: {
        titleRequired: 'Введите наименование задачи',
        titleTooLong: 'Не более 200 символов',
        descriptionTooLong: 'Не более 2000 символов',
        goalRequired: 'Выберите стратегическую цель',
        priorityRequired: 'Укажите приоритет',
      },
    },
    detail: {
      goalLabel: 'Стратегическая цель',
      priorityLabel: 'Приоритет',
      statusLabel: 'Статус',
      deadlineLabel: 'Срок',
      assigneeLabel: 'Исполнитель',
      createdAtLabel: 'Создана',
      createdByLabel: 'Автор',
      updatedAtLabel: 'Обновлена',
      descriptionLabel: 'Описание',
      noDescription: 'Описание не заполнено',
      noDeadline: 'Срок не указан',
    },
    actions: {
      edit: 'Редактировать',
      assign: 'Назначить исполнителя',
      reassign: 'Сменить исполнителя',
      changeStatus: 'Изменить статус',
      delete: 'Удалить задачу',
      confirmDelete: 'Удалить задачу без возможности восстановления?',
    },
    assignDialog: {
      title: 'Назначить исполнителя',
      subtitle: 'Выберите сотрудника из списка',
      assigneeLabel: 'Исполнитель',
      assigneePlaceholder: 'Выберите сотрудника',
      submit: 'Назначить',
      noEmployees: 'Нет доступных сотрудников',
    },
    statusDropdown: {
      label: 'Статус задачи',
      lockedReason: 'Сначала назначьте исполнителя',
    },
    status: {
      TODO: 'К выполнению',
      IN_PROGRESS: 'В работе',
      DONE: 'Завершена',
      BLOCKED: 'Заблокирована',
    },
    toast: {
      created: 'Задача создана',
      updated: 'Задача обновлена',
      assigned: 'Исполнитель назначен',
      statusChanged: 'Статус задачи обновлён',
      deleted: 'Задача удалена',
    },
  },
  reports: {
    analyticsTitle: 'Панель аналитики',
    analyticsSubtitle: 'Ключевые показатели и динамика портфеля инициатив',
    reportsTitle: 'Отчёты',
    reportsSubtitle: 'Сводные таблицы с выгрузкой в CSV',
    generatedBy: 'Сформировано пользователем',
    generatedAt: 'Дата формирования',
    empty: 'Нет данных',
    exportCsv: 'Экспортировать CSV',
    downloading: 'Скачивание…',
    overview: {
      goalsTotal: 'Всего целей',
      goalsActive: 'Активные цели',
      tasksTotal: 'Всего задач',
      tasksDone: 'Завершено задач',
      tasksOverdue: 'Просроченные задачи',
      backlogsSigned: 'Подписано бэклогов',
    },
    charts: {
      goalsProgressTitle: 'Прогресс по целям',
      goalsProgressYAxis: 'Задачи',
      goalsProgressDone: 'Завершено',
      goalsProgressPending: 'В работе',
      workloadTitle: 'Загрузка сотрудников по статусам',
      workloadYAxis: 'Задачи',
      workloadXAxis: 'Сотрудник',
      throughputTitle: 'Подписание бэклогов по месяцам',
      throughputYAxis: 'Бэклогов подписано',
      throughputXAxis: 'Период',
      unassigned: 'Не назначено',
    },
    tabs: {
      goalsProgress: 'Прогресс по целям',
      kpisProgress: 'Прогресс по KPI',
      taskWorkload: 'Загрузка сотрудников',
      overdueTasks: 'Просроченные задачи',
      backlogThroughput: 'Пропускная способность бэклогов',
    },
    columns: {
      goalTitle: 'Цель',
      goalStatus: 'Статус цели',
      totalTasks: 'Всего задач',
      doneTasks: 'Завершено',
      percent: 'Прогресс, %',
      kpiName: 'Показатель',
      kpiCurrent: 'Факт',
      kpiTarget: 'Цель',
      kpiUnit: 'Ед. изм.',
      assignee: 'Исполнитель',
      status: 'Статус',
      count: 'Количество',
      title: 'Наименование',
      deadline: 'Срок',
      daysOverdue: 'Дней просрочки',
      priority: 'Приоритет',
      period: 'Месяц',
      signedCount: 'Подписано',
      itemCount: 'Всего элементов',
    },
    toast: {
      exportFailed: 'Не удалось сформировать CSV',
    },
  },
  admin: {
    audit: {
      title: 'Журнал аудита',
      subtitle: 'История мутаций доменных сущностей и событий входа',
      empty: 'Записи журнала не найдены',
      emptyHint: 'Измените фильтры или выполните действие в системе',
      filters: {
        entityType: 'Тип объекта',
        entityTypePlaceholder: 'Например, Goal',
        entityTypeAll: 'Все типы',
        entityId: 'Идентификатор',
        entityIdPlaceholder: 'UUID или строковый ключ',
        performedBy: 'Автор',
        performedByAll: 'Все пользователи',
        from: 'Дата от',
        to: 'Дата до',
        pageSize: 'Строк на странице',
        reset: 'Сбросить фильтры',
        apply: 'Применить',
      },
      columns: {
        createdAt: 'Дата и время',
        actor: 'Автор',
        action: 'Действие',
        entityType: 'Тип объекта',
        entityId: 'Идентификатор',
        message: 'Сообщение',
        details: 'Детали',
      },
      action: {
        CREATE: 'Создание',
        UPDATE: 'Обновление',
        DELETE: 'Удаление',
        LOGIN_SUCCESS: 'Успешный вход',
        LOGIN_FAILURE: 'Ошибка входа',
      },
      details: {
        title: 'Детали изменения',
        none: 'Нет детальной информации об изменении',
        messageLabel: 'Сообщение',
        diffLabel: 'Данные изменения',
      },
      pagination: {
        prev: 'Назад',
        next: 'Вперёд',
        status: 'Страница {page} из {total}',
      },
      toast: {
        loadFailed: 'Не удалось загрузить журнал аудита',
      },
    },
    users: {
      title: 'Пользователи',
      subtitle: 'Список активных учётных записей и назначенных ролей',
      empty: 'Пользователи не найдены',
      columns: {
        fullName: 'Полное имя',
        username: 'Логин',
        role: 'Роль',
      },
      filters: {
        role: 'Роль',
        roleAll: 'Все роли',
      },
      toast: {
        loadFailed: 'Не удалось загрузить список пользователей',
      },
    },
  },
} as const

export type StringsTree = typeof strings
